// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {entities} from '../models';

export function AddCustomer(arg1:string):Promise<boolean>;

export function AddCustomerTime(arg1:number,arg2:number,arg3:time.Time,arg4:time.Time):Promise<boolean>;

export function DeleteCustomer(arg1:number):Promise<boolean>;

export function DeleteTime(arg1:number):Promise<void>;

export function ExportCustomer(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetCustomerTimes(arg1:number):Promise<Array<entities.TrackedTime>>;

export function GetCustomers():Promise<Array<entities.Customer>>;

export function UpdateCustomerTimeComment(arg1:number,arg2:string):Promise<void>;

export function UpdateCustomerTimeEndTime(arg1:number,arg2:string):Promise<void>;

export function UpdateCustomerTimeStartTime(arg1:number,arg2:string):Promise<void>;
