// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomer(arg1) {
  return window['go']['customerhandler']['CustomerHandler']['AddCustomer'](arg1);
}

export function AddCustomerTime(arg1, arg2, arg3, arg4) {
  return window['go']['customerhandler']['CustomerHandler']['AddCustomerTime'](arg1, arg2, arg3, arg4);
}

export function DeleteCustomer(arg1) {
  return window['go']['customerhandler']['CustomerHandler']['DeleteCustomer'](arg1);
}

export function DeleteTime(arg1) {
  return window['go']['customerhandler']['CustomerHandler']['DeleteTime'](arg1);
}

export function ExportCustomer(arg1, arg2, arg3) {
  return window['go']['customerhandler']['CustomerHandler']['ExportCustomer'](arg1, arg2, arg3);
}

export function GetCustomerTimes(arg1) {
  return window['go']['customerhandler']['CustomerHandler']['GetCustomerTimes'](arg1);
}

export function GetCustomers() {
  return window['go']['customerhandler']['CustomerHandler']['GetCustomers']();
}

export function UpdateCustomerTimeComment(arg1, arg2) {
  return window['go']['customerhandler']['CustomerHandler']['UpdateCustomerTimeComment'](arg1, arg2);
}

export function UpdateCustomerTimeEndTime(arg1, arg2) {
  return window['go']['customerhandler']['CustomerHandler']['UpdateCustomerTimeEndTime'](arg1, arg2);
}

export function UpdateCustomerTimeStartTime(arg1, arg2) {
  return window['go']['customerhandler']['CustomerHandler']['UpdateCustomerTimeStartTime'](arg1, arg2);
}
