// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCustomers() {
  return window['go']['customerhandler']['CustomerHandler']['GetCustomers']();
}

export function Greet(arg1) {
  return window['go']['customerhandler']['CustomerHandler']['Greet'](arg1);
}
