// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function AddCustomer(arg1:string):Promise<boolean>;

export function DeleteCustomer(arg1:number):Promise<boolean>;

export function GetCustomerTimes(arg1:number):Promise<Array<entities.TrackedTime>>;

export function GetCustomers():Promise<Array<entities.Customer>>;
